# Generated by Django 5.2.7 on 2025-10-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('waiting', 'Waiting on User'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='new', max_length=20),
        ),
    ]
